server:
  port: 8002

spring:
  application:
    name: orderdemo

eureka:
  instance:
    hostname: orderdemo8002
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://EurekaServer7001:7001/eureka/,http://EurekaServer7002:7002/eureka/