server:
  port: 7002

spring:
  application:
    name: eurekaServer

eureka:
  instance:
    hostname: eurekaServer7002
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://EurekaServer7001:7001/eureka/