server:
  port: 8000

spring:
  application:
    name: orderdemo

eureka:
  instance:
    hostname: orderdemo8000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/